### ISSUE TITLE
Docker image tag doesn't match commit hash

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/.github#86]
## Context

https://github.com/celestiaorg/celestia-app/actions/runs/6707478639/job/18226474489#step:6:598

## Problem

docker-security-build pushed a Docker image with a hash that doesn't match the most recent commit on that PR. The image tag contains `50d0f77` but the commit is https://github.com/celestiaorg/celestia-app/pull/2794/commits/6aa2f8884eb59405c4410f59d461e24d8da55569.

**Comment by MSevey** [comment]
I assume this is resolved by now.
